[project]
name = "timelined_array"
description = "Manage easily 1 or multidimensionnal samples numpy arrays that are time related. Extends numpy without removing any of it's abilities on such arrays."
authors = [
    { name = "Timothe Jost", email = "44769559+JostTim@users.noreply.github.com" },
]
version = "0.1.2"
dependencies = ["numpy>=2"]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
"Homepage" = "https://pypi.org/project/timelined_array/"
"Source" = "https://github.com/JostTim/timelined_array"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0"
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.ty.rules]
invalid-method-override = "ignore"

[tool.ruff]
ignore = ["B010", "PIE796"]

[tool.pytest.ini_options]
addopts = "-ra -q --pdbcls=IPython.terminal.debugger:TerminalPdb --cov-report xml --cov=timelined_array --junitxml=pytest_results.xml --cov-config=pyproject.toml"
testpaths = ["tests"]

[tool.coverage.run]
omit = [".vscode/*", ".tests/*"]

[tool.bumpversion]
current_version = "0.1.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "src/timelined_array/__init__.py"
